import { AIModel } from '../../types/ai';

/**
 * 10 Featured models for the FLOAT model selector with verified metadata structure.
 * 
 * Supports:
 * - id
 * - displayName
 * - shortName
 * - provider
 * - description
 * - contextWindow
 * - version
 * - reasoningLevel
 * - capabilities
 * - status
 * - isNew
 * - apiModelId
 * - supportsStreaming
 * - supportsTools
 * - supportsVision
 * - supportsReasoning
 * - availability
 */
export const DASHBOARD_MODELS: AIModel[] = [
  {
    id: 'grok-4.7',
    displayName: 'Grok 4.7 High Fast',
    shortName: 'Grok 4.7 (fast)',
    provider: 'xAI',
    providerId: 'xai',
    family: 'grok',
    description: "xAI's most powerful model, built for complex coding and knowledge work.",
    contextWindow: 262144,
    version: 'high effort',
    reasoningLevel: 'High Fast',
    capabilities: { coding: true, reasoning: true, tools: true, vision: false, structuredOutput: true, streaming: true, longContext: true },
    capabilitiesList: ['Coding', 'Reasoning', 'Tool use'],
    status: 'AVAILABLE',
    speed: 'fast',
    isNew: true,
    apiModelId: 'grok-2-1212',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: true,
    availability: 'Available'
  },
  {
    id: 'grok-4.6',
    displayName: 'Grok 4.6 High Fast',
    shortName: 'Grok 4.6 (fast)',
    provider: 'xAI',
    providerId: 'xai',
    family: 'grok',
    description: 'Frontier reasoning and code generation model designed for low latency and high throughput developer tasks.',
    contextWindow: 131072,
    version: 'high effort',
    reasoningLevel: 'High Fast',
    capabilities: { coding: true, reasoning: true, tools: true, vision: false, structuredOutput: true, streaming: true, longContext: true },
    capabilitiesList: ['Coding', 'Reasoning', 'Tool use'],
    status: 'AVAILABLE',
    speed: 'fast',
    isNew: false,
    apiModelId: 'grok-2',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: true,
    availability: 'Available'
  },
  {
    id: 'composer-2.5',
    displayName: 'Composer 2.5 Fast',
    shortName: 'Composer 2.5',
    provider: 'Google',
    providerId: 'google',
    family: 'composer',
    description: 'Low-latency agentic model optimized for fast interactive file edits, completions, and code generation.',
    contextWindow: 131072,
    version: 'fast latency',
    reasoningLevel: 'Fast',
    capabilities: { coding: true, reasoning: true, tools: true, vision: false, structuredOutput: true, streaming: true, longContext: false },
    capabilitiesList: ['Coding', 'Reasoning', 'Tool use'],
    status: 'AVAILABLE',
    speed: 'fast',
    isNew: false,
    apiModelId: 'gemini-3.8-flash',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: true,
    availability: 'Available'
  },
  {
    id: 'claude-opus-5.5',
    displayName: 'Claude Opus 5.5 Medium',
    shortName: 'Claude Opus 5.5',
    provider: 'Anthropic',
    providerId: 'anthropic',
    family: 'claude',
    description: 'A reasoning-focused model designed for complex software development, refactoring, and deep code analysis.',
    contextWindow: 200000,
    version: 'medium effort',
    reasoningLevel: 'Medium',
    capabilities: { coding: true, reasoning: true, tools: true, vision: true, structuredOutput: true, streaming: true, longContext: true },
    capabilitiesList: ['Coding', 'Reasoning', 'Tool use', 'Vision'],
    status: 'AVAILABLE',
    speed: 'balanced',
    isNew: false,
    apiModelId: 'claude-3-opus-20240229',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    availability: 'Available'
  },
  {
    id: 'claude-opus-5',
    displayName: 'Claude Opus 5 High',
    shortName: 'Claude Opus 5',
    provider: 'Anthropic',
    providerId: 'anthropic',
    family: 'claude',
    description: 'Flagship deep intelligence model built for multi-turn architectural design, proofs, and complex problem solving.',
    contextWindow: 200000,
    version: 'high effort',
    reasoningLevel: 'High',
    capabilities: { coding: true, reasoning: true, tools: true, vision: true, structuredOutput: true, streaming: true, longContext: true },
    capabilitiesList: ['Coding', 'Reasoning', 'Tool use', 'Vision'],
    status: 'AVAILABLE',
    speed: 'slow',
    isNew: false,
    apiModelId: 'claude-3-opus-20240229',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    availability: 'Available'
  },
  {
    id: 'gpt-5.6-sol',
    displayName: 'GPT-5.6 Sol Medium',
    shortName: 'GPT-5.6 Sol',
    provider: 'OpenAI',
    providerId: 'openai',
    family: 'gpt',
    description: 'A general-purpose advanced reasoning model optimized for full-stack software development and tool workflows.',
    contextWindow: 131072,
    version: 'medium effort',
    reasoningLevel: 'Medium',
    capabilities: { coding: true, reasoning: true, tools: true, vision: true, structuredOutput: true, streaming: true, longContext: true },
    capabilitiesList: ['Coding', 'Reasoning', 'Tool use', 'Vision'],
    status: 'AVAILABLE',
    speed: 'balanced',
    isNew: false,
    apiModelId: 'gpt-4o-2024-11-20',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    availability: 'Available'
  },
  {
    id: 'claude-fable-5.1',
    displayName: 'Claude Fable 5.1 High',
    shortName: 'Claude Fable 5.1',
    provider: 'Anthropic',
    providerId: 'anthropic',
    family: 'claude',
    description: 'Advanced technical reasoning and architectural synthesis model for ambitious full-stack engineering tasks.',
    contextWindow: 200000,
    version: 'high effort',
    reasoningLevel: 'High',
    capabilities: { coding: true, reasoning: true, tools: true, vision: true, structuredOutput: true, streaming: true, longContext: true },
    capabilitiesList: ['Coding', 'Reasoning', 'Tool use', 'Vision'],
    status: 'AVAILABLE',
    speed: 'slow',
    isNew: false,
    apiModelId: 'claude-3-7-sonnet-20250219',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    availability: 'Available'
  },
  {
    id: 'gemini-3.8-flash',
    displayName: 'Gemini 3.8 Flash High',
    shortName: 'Gemini 3.8 Flash',
    provider: 'Google',
    providerId: 'google',
    family: 'gemini',
    description: 'A fast, high-capability model designed for responsive coding, multimodal analysis, and large-context workflows.',
    contextWindow: 1048576,
    version: 'high effort',
    reasoningLevel: 'High',
    capabilities: { coding: true, reasoning: true, tools: true, vision: true, structuredOutput: true, streaming: true, longContext: true },
    capabilitiesList: ['Coding', 'Reasoning', 'Tool use', 'Vision'],
    status: 'AVAILABLE',
    speed: 'fast',
    isNew: false,
    apiModelId: 'gemini-3.8-flash',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    availability: 'Available'
  },
  {
    id: 'muse-spark-1.3',
    displayName: 'Muse Spark 1.3 High',
    shortName: 'Muse Spark 1.3',
    provider: 'Google',
    providerId: 'google',
    family: 'muse',
    description: 'Specialized creative ideation and technical planning model with high reasoning capacity and rapid response.',
    contextWindow: 131072,
    version: 'high effort',
    reasoningLevel: 'High',
    capabilities: { coding: true, reasoning: true, tools: true, vision: false, structuredOutput: true, streaming: true, longContext: false },
    capabilitiesList: ['Coding', 'Reasoning', 'Tool use'],
    status: 'AVAILABLE',
    speed: 'fast',
    isNew: false,
    apiModelId: 'gemini-3.8-flash',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: true,
    availability: 'Available'
  },
  {
    id: 'claude-sonnet-5.5',
    displayName: 'Claude Sonnet 5.5 High',
    shortName: 'Claude Sonnet 5.5',
    provider: 'Anthropic',
    providerId: 'anthropic',
    family: 'claude',
    description: 'Highly capable balanced model optimized for fast, accurate full-stack code development and intelligent debugging.',
    contextWindow: 200000,
    version: 'high effort',
    reasoningLevel: 'High',
    capabilities: { coding: true, reasoning: true, tools: true, vision: true, structuredOutput: true, streaming: true, longContext: true },
    capabilitiesList: ['Coding', 'Reasoning', 'Tool use', 'Vision'],
    status: 'AVAILABLE',
    speed: 'balanced',
    isNew: false,
    apiModelId: 'claude-3-5-sonnet-20241022',
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    availability: 'Available'
  }
];
